inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '*.gemspec'

Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/CommandLiteral:
  EnforcedStyle: percent_x

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

#  vim: set ts=8 sw=2 tw=0 ft=yaml et :
